#deployment yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linux_tweet_app
spec:
  replicas: 2
  selector:
    matchlabels:
      app: linux_tweet_app
  template:
    metadata:
      labels:
        app: linux_tweet_app
    spec:
      containers:
      - name: linux_tweet_app
      image: testdemonns.azurecr.io/linux_tweet_app:latest
      imagepullpolicy: Always
      ports:
      - containerport: 80
#service yaml

apiVersion: v1
kind: Service
metadata:
  name: linux_tweet_app
spec:
  selector:
    app: linux_tweet_app
  ports:
    - protocal: TCP
      port: 80
      targetport: 80